### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by owii03** [ryan-parag/ryanparag.com#53]
Hi Ryan, I'm impress to see your portfolio! Admire the design simplicity and also the development. If I may ask,
![Screen Shot 2021-12-17 at 11 04 34](https://user-images.githubusercontent.com/38784896/146487481-63d85043-fd9c-4f57-b09a-b4d438943596.png)
Could you and would you share how to make the code for one of the project/portfolio being protected (just like the image)? I tried to find it in your current code, but I'm not sure it's there. But, if it's okay with you. Thankyou, have a great day!

**Comment by ryan-parag** [comment]
Hey Glo, apologize about the delayed response.

Thanks for taking a look at my portfolio! It's definitely been a never-ending process of small iterations.

1. It looks like this password-protection is located in my [older/ Gatsby portfolio](https://work.ryanparag.com). I moved this to a private-repo, but this solution was done a bit poorly - the password could be found out if someone dug through the source, so I was never able to make the repo public. My [newer portfolio](https://ryanparag.com) has a much more secure password-protection, in this case, I'm using it to uncover admin editing capabilities for myself. I have the login page on an [unlisted page](https://ryanparag.com/login), but basically, I'm using Notion as a database for my portfolio data so when the user submits this form, the UI checks if the input matches a value in Notion. For more secure solutions, I know 3rd-party services, like Auth0 work great!

![image](https://user-images.githubusercontent.com/22060683/147002188-12d0e86f-8f91-427e-9d9c-f73f46a49dc9.png)
[Here's the code to my latest password page using NextJS and Notion](https://github.com/ryan-parag/ryanparag.com/blob/master/pages/login.js)

2. Yeah, this one confused me as well - since I'm not really a developer. It took a bit of trying, but there were alot of other helpful methods from others:
- https://benwiz.com/blog/create-spotify-refresh-token/
- https://alecchendev.medium.com/get-your-spotify-refresh-token-with-this-simple-web-app-d942dad05847 (I didn't even know about this, it looks super helpful)

Some googling around "Spotify API javascript" should bring up some helpful tutorials

3. This is loading for your localhost because it requires the .env variables (the notion database id's) to build (and that is not public on github). This data is coming from Notion
image.png
4. I was previously using Airtable as my database for things, like Featured, but have since moved to Notion. There are probably some very helpful tutorials on how to use NextJS with the Notion API

Hopefully that helps, but let me know if I can clarify anything.

Thanks!
- Ryan
